### ISSUE TITLE
Unable to Load svg image found below error 

### ISSUE THREAD

**Issue by kamarajuPrathi** [boopathi/react-svg-loader#141]
I am using this library for first time , i found the below issue 

bundle.js:79052 Uncaught Error: Module build failed: ReferenceError: window is not defined
    at Object.<anonymous> (/node_modules/svg-injector/svg-injector.js:464:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
   

Please let me know how to fix it

**Comment by boopathi** [comment]
I'm not able to understand what you're doing. Looks like some code that is meant to be executed on the client is executed in nodejs.

**Comment by kamarajuPrathi** [comment]
Yes .. I have followed the steps , I got that error
