### ISSUE TITLE
Unable to convert svg to component

### ISSUE THREAD

**Issue by nicholasrq** [boopathi/react-svg-loader#142]
Hello.

Getting this error:

```
ERROR in ./assets/images/wv-icons.svg
Module parse failed: /Users/.../node_modules/react-svg-loader/lib/loader.js?{"jsx":true,"svgo":{"plugins":[{"removeXMLNS":true},{"removeTitle":true},{"removeUselessDefs":false},{"removeHiddenElems":false},{"cleanupIDs":false}]}}!/Users/.../assets/images/wv-icons.svg Unexpected token (4:11)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (4:11)
    at Parser.pp$4.raise (/Users/.../node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/.../node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/Users/.../node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/Users/.../node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/Users/.../node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/.../node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/.../node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/.../node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/Users/.../node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseReturnStatement (/Users/.../node_modules/acorn/dist/acorn.js:839:33)
 @ ./assets/javascripts/player/ui.js 15:15-45
```

Webpack 1.14.0

config:

```javascript
{
  "resolve": {
    "alias": {
      "lib": "/Users/.../lib",
      "build": "/Users/.../build",
      "config": "/Users/.../config",
      "fixture": "/Users/.../fixture",
      "poly": "/Users/.../polyfills",
      "player": "/Users/.../assets/javascripts/player",
      "js": "/Users/.../assets/javascripts",
      "app": "/Users/.../assets/javascripts/app",
      "images": "/Users/.../assets/images"
    },
    "extensions": [
      "",
      ".js"
    ]
  },
  "output": {
    "filename": "player_ui.js",
    "library": "PlayerUI"
  },
  "plugins": [
    {
      "definitions": {
        "Utils": [
          "lib/shared/utils",
          "default"
        ],
        "Map": [
          "poly/es6-map",
          "default"
        ],
        "Set": [
          "poly/es6-set",
          "default"
        ],
        "Symbol": [
          "poly/es6-symbol",
          "default"
        ],
        "Promise": [
          "lib/polyfill",
          "Promise"
        ],
        "console": [
          "lib/console",
          "default"
        ],
        "React": "react",
        "ReactDOM": "react-dom",
        "linkRef": [
          "lib/linked-ref",
          "default"
        ]
      }
    },
    {
      "definitions": {
        "process.env": {
          "NODE_ENV": "\"development\""
        }
      }
    }
  ],
  "module": {
    "loaders": [
      {
        "test": /\.js(x)?$/,
        "loader": "babel",
        "exclude": "/node_modules\\/es6\\-*./",
        "query": {
          "plugins": [
            "transform-function-bind",
            "transform-class-properties",
            "transform-object-rest-spread"
          ],
          "presets": [
            "react",
            "latest"
          ]
        }
      },
      {
        "test": /\.svg$/,
        "loader": "react-svg",
        "query": {
          "jsx": true,
          "svgo": {
            "plugins": [
              {
                "removeXMLNS": true
              },
              {
                "removeTitle": true
              },
              {
                "removeUselessDefs": false
              },
              {
                "removeHiddenElems": false
              },
              {
                "cleanupIDs": false
              }
            ]
          }
        }
      }
    ]
  },
  "devtool": "source-map"
}
```

**Comment by nicholasrq** [comment]
Also with CLI tool everything works just fine.

**Comment by nicholasrq** [comment]
I've also tried to use this

```javascript
import Icons from 'react-svg!images/wv-icons.svg'
```

Same error:

```
ERROR in ./~/react-svg-loader/lib/loader.js!./assets/images/wv-icons.svg
Module parse failed: /Users/.../node_modules/react-svg-loader/lib/loader.js!/Users/.../assets/images/wv-icons.svg Unexpected token (4:11)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (4:11)
    at Parser.pp$4.raise (/Users/.../node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/.../node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/Users/.../node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/Users/.../node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/Users/.../node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/.../node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/.../node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/.../node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/Users/.../node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseReturnStatement (/Users/.../node_modules/acorn/dist/acorn.js:839:33)
 @ ./assets/javascripts/player/ui.js 15:15-55
```

**Comment by boopathi** [comment]
You're passing `jsx: true` which outputs JSX - webpack doesn't understand jsx. You have to use jsx false.
