### ISSUE TITLE
Error on svgo

### ISSUE THREAD

**Issue by exdeniz** [boopathi/react-svg-loader#163]
I have this error after update.

```
Module build failed: Error: ENOENT: no such file or directory, open '/Users/exdeniz/Project/reinvent/site/node_modules/react-svg-loader/node_modules/svgo/lib/svgo/../../.svgo.yml'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at module.exports (/Users/exdeniz/Project/reinvent/site/node_modules/react-svg-loader/node_modules/svgo/lib/svgo/config.js:31:48)
    at new module.exports (/Users/exdeniz/Project/reinvent/site/node_modules/react-svg-loader/node_modules/svgo/lib/svgo.js:21:19)
    at optimize (/Users/exdeniz/Project/reinvent/site/node_modules/react-svg-loader/lib/loader.js:45:14)
    at Object.exports.default (/Users/exdeniz/Project/reinvent/site/node_modules/react-svg-loader/lib/loader.js:14:41)
```
webpack 2.0
```
{
        test: /\.svg$/,
        loaders: [
          'babel-loader',
          {
            loader: 'react-svg-loader',
            query: {
              jsx: true,
            },
          },
        ],
      },
```

**Comment by dalgleish** [comment]
That file exists for me.
Can you try clearing your node_modules?
`cd /Users/exdeniz/Project/reinvent/site && rm -fr node_modules && npm install`

**Comment by exdeniz** [comment]
I investigated this bug. It's because of what I'm using yarn. ```npm install``` work correct.

**Comment by boopathi** [comment]
Closing this as it doesn't look like a bug.
