### ISSUE TITLE
Unable to use global svg2react cli

### ISSUE THREAD

**Issue by donysukardi** [boopathi/react-svg-loader#191]
I'm getting unknown plugin error when I try to run global svg2react cli

```
REACT-SVG-LOADER ERROR ic_filter_list_24px.svg ReferenceError: Unknown plugin "syntax-jsx" specified in "base" at 0, attempted to resolve relative to "/Users/donysukardi/Desktop"
    at /Users/donysukardi/.config/yarn/global/node_modules/react-svg-core/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/donysukardi/.config/yarn/global/node_modules/react-svg-core/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/donysukardi/.config/yarn/global/node_modules/react-svg-core/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/donysukardi/.config/yarn/global/node_modules/react-svg-core/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/donysukardi/.config/yarn/global/node_modules/react-svg-core/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/donysukardi/.config/yarn/global/node_modules/react-svg-core/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/donysukardi/.config/yarn/global/node_modules/react-svg-core/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at /Users/donysukardi/.config/yarn/global/node_modules/react-svg-core/lib/index.js:48:37
    at <anonymous>
```

**Comment by boopathi** [comment]
Thanks.

`babel-plugin-syntax-jsx` isn't found in your node_modules. Should probably include import that instead of letting babel resolve the plugin. PR welcome.
