### ISSUE TITLE
Cause a Invariant Violation error with mocha when enzyme mounting it.

### ISSUE THREAD

**Issue by dqisme** [boopathi/react-svg-loader#36]
I use this loader in my component like this(with webpack config): 

```javascript
import Icon from './icon.svg';

...
export default class MyComponent extends React.Component {
    ...
    render() {
        ...
        <Icon style={...} />
    }
}
```

and I use `mocha` for my test driver and `enzyme` as testing framework,

```javascript
import { mount, shallow, render } from 'enzyme';

describe('...', () => {
    it('...', () =>{
        const wrapper = mount(<MyComponent />);
    });
});
```

Here. When `enzyme` mount the component, it will mount the "`react-svg`ified" Icon into `jsdom`, and it will occurs an **Invariant Violation**.

*Selection is my component.*

```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `Selection`.
      at invariant (node_modules/fbjs/lib/invariant.js:38:15)
      at instantiateReactComponent (node_modules/react/lib/instantiateReactComponent.js:66:134)
      at instantiateChild (node_modules/react/lib/ReactChildReconciler.js:29:28)
      at traverseAllChildrenImpl (node_modules/react/lib/traverseAllChildren.js:67:5)
      at traverseAllChildren (node_modules/react/lib/traverseAllChildren.js:155:10)
      at Object.ReactChildReconciler.instantiateChildren (node_modules/react/lib/ReactChildReconciler.js:52:5)
      at ReactDOMComponent.ReactMultiChild.Mixin._reconcilerInstantiateChildren (node_modules/react/lib/ReactMultiChild.js:159:41)
      at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (node_modules/react/lib/ReactMultiChild.js:196:27)
      at ReactDOMComponent.Mixin._createInitialChildren (node_modules/react/lib/ReactDOMComponent.js:628:32)
      at ReactDOMComponent.Mixin.mountComponent (node_modules/react/lib/ReactDOMComponent.js:474:12)
      at ReactDOMComponent.wrapper [as mountComponent] (node_modules/react/lib/ReactPerf.js:66:21)
      at Object.ReactReconciler.mountComponent (node_modules/react/lib/ReactReconciler.js:39:35)
      at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (node_modules/react/lib/ReactMultiChild.js:203:44)
      at ReactDOMComponent.Mixin._createInitialChildren (node_modules/react/lib/ReactDOMComponent.js:628:32)
      at ReactDOMComponent.Mixin.mountComponent (node_modules/react/lib/ReactDOMComponent.js:474:12)
      at ReactDOMComponent.wrapper [as mountComponent] (node_modules/react/lib/ReactPerf.js:66:21)
      at Object.ReactReconciler.mountComponent (node_modules/react/lib/ReactReconciler.js:39:35)
      at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (node_modules/react/lib/ReactMultiChild.js:203:44)
      at ReactDOMComponent.Mixin._createInitialChildren (node_modules/react/lib/ReactDOMComponent.js:628:32)
      at ReactDOMComponent.Mixin.mountComponent (node_modules/react/lib/ReactDOMComponent.js:474:12)
      at ReactDOMComponent.wrapper [as mountComponent] (node_modules/react/lib/ReactPerf.js:66:21)
      at Object.ReactReconciler.mountComponent (node_modules/react/lib/ReactReconciler.js:39:35)
      at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (node_modules/react/lib/ReactMultiChild.js:203:44)
      at ReactDOMComponent.Mixin._createInitialChildren (node_modules/react/lib/ReactDOMComponent.js:628:32)
      at ReactDOMComponent.Mixin.mountComponent (node_modules/react/lib/ReactDOMComponent.js:474:12)
      at ReactDOMComponent.wrapper [as mountComponent] (node_modules/react/lib/ReactPerf.js:66:21)
      at Object.ReactReconciler.mountComponent (node_modules/react/lib/ReactReconciler.js:39:35)
      at [object Object].ReactCompositeComponentMixin.performInitialMount (node_modules/react/lib/ReactCompositeComponent.js:297:34)
      at [object Object].ReactCompositeComponentMixin.mountComponent (node_modules/react/lib/ReactCompositeComponent.js:222:21)
      at [object Object].wrapper [as mountComponent] (node_modules/react/lib/ReactPerf.js:66:21)
      at Object.ReactReconciler.mountComponent (node_modules/react/lib/ReactReconciler.js:39:35)
      at [object Object].ReactCompositeComponentMixin.performInitialMount (node_modules/react/lib/ReactCompositeComponent.js:297:34)
      at [object Object].ReactCompositeComponentMixin.mountComponent (node_modules/react/lib/ReactCompositeComponent.js:222:21)
      at [object Object].wrapper [as mountComponent] (node_modules/react/lib/ReactPerf.js:66:21)
      at Object.ReactReconciler.mountComponent (node_modules/react/lib/ReactReconciler.js:39:35)
      at [object Object].ReactCompositeComponentMixin.performInitialMount (node_modules/react/lib/ReactCompositeComponent.js:297:34)
      at [object Object].ReactCompositeComponentMixin.mountComponent (node_modules/react/lib/ReactCompositeComponent.js:222:21)
      at [object Object].wrapper [as mountComponent] (node_modules/react/lib/ReactPerf.js:66:21)
      at Object.ReactReconciler.mountComponent (node_modules/react/lib/ReactReconciler.js:39:35)
      at mountComponentIntoNode (node_modules/react/lib/ReactMount.js:103:32)
      at ReactReconcileTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:136:20)
      at batchedMountComponentIntoNode (node_modules/react/lib/ReactMount.js:124:15)
      at ReactDefaultBatchingStrategyTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:136:20)
      at Object.ReactDefaultBatchingStrategy.batchedUpdates (node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
      at Object.batchedUpdates (node_modules/react/lib/ReactUpdates.js:97:20)
      at Object.ReactMount._renderNewRootComponent (node_modules/react/lib/ReactMount.js:277:18)
      at Object.wrapper [as _renderNewRootComponent] (node_modules/react/lib/ReactPerf.js:66:21)
      at Object.ReactMount._renderSubtreeIntoContainer (node_modules/react/lib/ReactMount.js:354:32)
      at Object.ReactMount.render (node_modules/react/lib/ReactMount.js:374:23)
      at Object.wrapper [as render] (node_modules/react/lib/ReactPerf.js:66:21)
      at Object.ReactTestUtils.renderIntoDocument (node_modules/react/lib/ReactTestUtils.js:78:21)
      at renderWithOptions (node_modules/enzyme/build/react-compat.js:175:26)
      at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:87:59)
      at mount (node_modules/enzyme/build/mount.js:21:10)
      at Context.<anonymous> (selection.test.js:14:21)
```

I use something like `null-loader` to ignore styling import and I wonder whether there are some ways to make `mocha`/`enzyme` know what the Icon is or ignore it.

Need Your Help. Thank you guys.

**Comment by boopathi** [comment]
Can you print and see what that object's keys are ?

If it's "default", then you don't have a `module.exports = Icon`, instead you have a `exports.default = Icon`. This should be fixable by adding a babel plugin while transpiling.

If it's something else, then we'll find what the bug is with some sample project.

**Comment by dqisme** [comment]
@boopathi 
I use `node-inspector` jump into `mocha` test and then I get the **object** here:

```javascript
{
    "key": null,
    "ref": null,
    "props": {
        "key": null,
        "ref": null,
        "props": {
            "props": {},
            "context": null
        },
        "_owner": null,
        "_store": {}
    },
    "_owner": null,
    "_store": {}
}
```

**Comment by boopathi** [comment]
Hmm.. I'm not able to reproduce. 
Tried it out here -
https://github.com/boopathi/__react-svg-loader-bug-36

**Comment by dqisme** [comment]
@boopathi okay and I forked your repo and push my code in it here - [https://github.com/dqisme/__react-svg-loader-bug-36](https://github.com/dqisme/__react-svg-loader-bug-36)
I used null-compiler to ignore svg import in case mocha will run svg xml code which confuse it as es6 script.

**Comment by boopathi** [comment]
What nodejs are you testing on ? I'm not able to debug more into the issue. Transpiling and testing works fine.

And `require.extensions` is a **deprecated** feature and I'd recommend not depending on it (with null-compiler).
https://nodejs.org/api/globals.html#globals_require_extensions 

I don't know how this might be a problem with react-svg-loader

**Comment by dqisme** [comment]
@boopathi I will try it AFAIK. If we load SVG in mocha, the mocha will consider SVG as normal JavaScript code and fail. If we do not load SVG by null-compiler, React will consider this import as an invalid object as the error message.  So we must find a way to mock the SVG import up to pass mocha test.

**Comment by dqisme** [comment]
Finally, I find a package [require-hacker](https://github.com/halt-hammerzeit/require-hacker) which doesn't use `require.extension` to add hooks to `.svg` module. And I use it with a null react component mock to make `mocha` can import SVG as `react-svg-loader` way.

and I create a pull request to you here
[https://github.com/boopathi/__react-svg-loader-bug-36/pull/1](https://github.com/boopathi/__react-svg-loader-bug-36/pull/1)

**Comment by boopathi** [comment]
Awesome. Thanks a lot for digging more into this. Would you like to send a PR to update the docs for mocking svg to this Repo ?

**Comment by dqisme** [comment]
Cool! I d like to. I will create pr to describe that when free👌
